# Generated by Django 4.0.2 on 2022-02-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_blogpost_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
