# Generated by Django 4.0.2 on 2022-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beautyflowers/static/img/')),
                ('alt', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
