# Generated by Django 4.0.2 on 2022-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyflowers', '0005_alter_product_alt_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
