# Generated by Django 4.0.2 on 2022-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyflowers', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=0),
        ),
    ]
