# Generated by Django 4.0.2 on 2022-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyflowers', '0007_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Exclusive one-size poster.'),
        ),
    ]
